// src/services/AccountService.js
const { SquareClient, SquareEnvironment } = require('square');

const square = new SquareClient({
  token: process.env.SQUARE_ACCESS_TOKEN,
  environment: process.env.NODE_ENV === 'production' 
    ? SquareEnvironment.Production 
    : SquareEnvironment.Sandbox,
});

class AccountService {
  /**
   * Initializes a new paid subscription layer for a registered user
   */
  async initializeSubscription(userId, { name, email, cardNonce }) {
    try {
      // 1. Register or find the customer profile inside Square's engine
      const customerResponse = await square.customers.create({
        givenName: name.split(' ')[0] || name,
        familyName: name.split(' ')[1] || '',
        emailAddress: email,
        referenceId: userId.toString() // Link our DB primary key to Square
      });
      const squareCustomerId = customerResponse.customer.id;

      // 2. Attach the secure card token safely to their Customer profile
      const cardResponse = await square.cards.create({
        card: {
          customerId: squareCustomerId,
          referenceId: userId.toString()
        },
        sourceId: cardNonce // This is the cnon: generated by the frontend SDK
      });
      const squareCardId = cardResponse.card.id;

      // 3. Bind the customer profile to your subscription plan
      const subscriptionResponse = await square.subscriptions.create({
        idempotencyKey: `sub-${userId}-${Date.now()}`, // Prevent accidental double billing
        locationId: process.env.SQUARE_LOCATION_ID,
        planVariationId: process.env.SQUARE_PLAN_VARIATION_ID, // Tier ID from Square dashboard
        customerId: squareCustomerId,
        cardId: squareCardId
      });

      // 4. Commit values smoothly into your local user database
      const updatedUser = await db.users.update(userId, {
        squareCustomerId: squareCustomerId,
        squareSubscriptionId: subscriptionResponse.subscription.id,
        subscriptionStatus: 'ACTIVE',
        billingTier: 'premium'
      });

      return { success: true, user: updatedUser };
    } catch (error) {
      console.error('AccountService Subscription Failure:', error);
      throw new Error(`Billing initialization failed: ${error.message}`);
    }
  }

  /**
   * Safe execution handler to trigger graceful end-of-cycle cancellations
   */
  async requestCancellation(userId, subscriptionId) {
    try {
      // Telling Square to terminate at the explicit billing period end
      await square.subscriptions.cancel({
        subscriptionId: subscriptionId
      });

      // Note: We leave subscriptionStatus as 'ACTIVE' but flag the imminent cancellation
      await db.users.update(userId, {
        cancelAtPeriodEnd: true
      });

      return { success: true };
    } catch (error) {
      console.error('AccountService Cancellation Failure:', error);
      throw error;
    }
  }
}

module.exports = new AccountService();